server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    appname: debt
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: debt

